#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ──────────────────────────────────────────────────────────────────────────
# friens-cal — issue 14: the allowlist, and the signup gate that reads it.
#
# Two of issue 14's nine acceptance criteria cannot be done from a repo. This
# walks both, plus the seeding and the one acceptance run that go with them.
#
#   1. paste supabase/07-allowlist.sql into the SQL Editor
#   2. seed the real Friends' addresses      (typed here, never written down)
#   3. register the before-user-created hook (a dashboard switch)
#   4. confirm that Confirm Email is still off
#   5. node --env-file=.env scripts/verify-allowlist.mjs
#   6. the one acceptance signup, by a real Friend
#
# NOTHING IS WRITTEN TO .env. Every value this wizard handles is somebody's
# personal email address, and the point of the allowlist is that those live in
# one Postgres table and nowhere else — not in the repo, not in .env, not in
# your shell history. Stage 2 puts a statement on your clipboard and forgets it.
#
# Safe to stop and re-run at any stage. Stages 1–5 create nothing. Stage 6
# creates an account, and stage 6 is the only step here that cannot be undone
# from anywhere but the dashboard.
# ──────────────────────────────────────────────────────────────────────────

# Every path below is relative to the repo root — the SQL file, .env, the verify
# script — so go there rather than depending on where this was invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# The dashboard URLs need the project ref, which is the first label of
# VITE_SUPABASE_URL. `_` is Supabase's own "whichever project I had open last"
# placeholder, so a missing .env costs a click rather than the whole run.
PROJECT_REF="_"
if [[ -f .env ]]; then
  _url=$(grep -E '^VITE_SUPABASE_URL=' .env | tail -n1 | cut -d= -f2- || true)
  _url=${_url#https://}
  _url=${_url%%.supabase.co*}
  [[ -n "$_url" ]] && PROJECT_REF="$_url"
fi
DASH="https://supabase.com/dashboard/project/${PROJECT_REF}"

# copy_stdin puts what it is given on the clipboard, and says so. Best-effort:
# on a machine with no clipboard the human pastes from the file instead, which
# every stage tells them how to do anyway.
copy_stdin() {
  if   command -v pbcopy   >/dev/null 2>&1; then pbcopy
  elif command -v wl-copy  >/dev/null 2>&1; then wl-copy
  elif command -v xclip    >/dev/null 2>&1; then xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then clip.exe
  else cat >/dev/null; return 1
  fi
}

banner "friens-cal — allowlist and signup (issue 14)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The SQL: the table, the gate, the grants"
say "supabase/07-allowlist.sql creates the allowlist, the before-user-created"
say "hook function that reads it, and the grants that let only the Auth server"
say "call that function. It seeds nothing — that is stage 2."
printf '\n'
open_url "${DASH}/sql/new"
if copy_stdin < supabase/07-allowlist.sql; then
  note "the whole file is on your clipboard"
else
  note "no clipboard here — open supabase/07-allowlist.sql and copy it by hand"
fi
step "Paste the whole file into the SQL Editor and Run it."
step "Expect 'Success. No rows returned'."
printf '\n'
note "Re-running it is safe: create table if not exists, create or replace"
note "function, and no inserts anywhere in it."
printf '\n'
pause "Run it, then press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Seed: who is allowed to sign up"
say "One row per Friend. Type an address, then who it belongs to."
say "Leave the address blank when you are done."
printf '\n'
warn "these are real people's email addresses: they go to Postgres and nowhere else"
printf '\n'

VALUES=""
COUNT=0
while true; do
  ask SEED_EMAIL "Email (blank to finish):"
  [[ -z "${SEED_EMAIL:-}" ]] && break
  SEED_EMAIL=$(printf '%s' "$SEED_EMAIL" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
  # The table has `check (email = lower(email))`, so a capital would be
  # rejected by Postgres rather than silently never matching. Lower-casing here
  # means a pasted address just works.
  ask SEED_NOTE "  ...and who is that?"
  # Single quotes are what would break the statement; doubling them is how SQL
  # escapes one.
  _e=${SEED_EMAIL//\'/\'\'}
  _n=${SEED_NOTE//\'/\'\'}
  [[ -n "$VALUES" ]] && VALUES="${VALUES},"$'\n'
  VALUES="${VALUES}  ('${_e}', '${_n}')"
  COUNT=$((COUNT + 1))
  note "  queued ${SEED_EMAIL}"
done

if (( COUNT == 0 )); then
  warn "nothing to seed — skipping. Nobody can sign up until this table has rows."
  SKIPPED+=("seed the allowlist (stage 2 of this wizard, or the statement in supabase/07-allowlist.sql §2)")
  pause "Press Enter."
else
  SEED_SQL="insert into public.allowlist (email, note) values
${VALUES}
on conflict (email) do nothing;"
  printf '\n'
  say "This is the statement. ${COUNT} address(es):"
  printf '\n%s%s%s\n\n' "$DIM" "$SEED_SQL" "$RESET"
  open_url "${DASH}/sql/new"
  if printf '%s\n' "$SEED_SQL" | copy_stdin; then
    note "it is on your clipboard"
  else
    note "no clipboard here — copy it from the screen above"
  fi
  step "Paste it into the SQL Editor and Run it."
  step "Adding someone later is this same statement, one row. Nothing else."
  printf '\n'
  pause "Run it, then press Enter."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Register the hook"
say "The function from stage 1 does nothing at all until this switch is on."
say "Until then signUp() succeeds for ANY address."
printf '\n'
open_url "${DASH}/auth/hooks"
step "Find 'Before User Created' and enable it."
step "Type: Postgres"
step "Schema: public"
step "Function: hook_restrict_signup_to_allowlist"
step "Save."
printf '\n'
warn "nothing can read this setting back over the Data API"
note "So stage 5 cannot check it politely. It checks it by trying a signup that"
note "should fail — and if this switch is off, that signup SUCCEEDS and leaves"
note "an account behind that nothing in the repo can delete. Do this one first."
printf '\n'
pause "Enabled and saved? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm Email stays off"
say "Ticket 13 disabled it, and that decision is safe only because the hook"
say "from stage 3 exists: an unconfirmed address can never be a stranger's."
printf '\n'
open_url "${DASH}/auth/providers"
step "Open the Email provider."
step "'Confirm email' should be OFF. Leave it off."
printf '\n'
note "If it is on, a new Friend waits for a mail Supabase will not deliver —"
note "its default mailer refuses every address that is not a project team"
note "member. Turning it on also breaks the signup screen's error handling,"
note "which is written down in src/auth/session-provider.tsx."
printf '\n'
pause "Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify: every lock, from a browser-shaped client"
say "scripts/verify-allowlist.mjs proves the four things it can prove without"
say "creating anything: the table is unreadable to anon and to a signed-in"
say "Friend, the hook is not callable over the Data API, an already-registered"
say "address is refused, and an address that is not on the list cannot sign up."
printf '\n'
if confirm "Run it now?"; then
  printf '\n'
  if node --env-file=.env scripts/verify-allowlist.mjs; then
    printf '\n'
    note "green. Stages 1 to 4 landed."
  else
    printf '\n'
    warn "it failed — read what it printed above before going on"
    warn "if it says an account was created, delete that account first"
    SKIPPED+=("scripts/verify-allowlist.mjs is failing")
  fi
else
  SKIPPED+=("node --env-file=.env scripts/verify-allowlist.mjs")
fi
printf '\n'
pause "Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The acceptance run — one real Friend, once"
say "The last criterion is that an address ON the list can sign up and lands in"
say "the setup flow. There is no way to test that without creating an account."
printf '\n'
warn "this is the one step here that cannot be undone from the app"
note "A completed signup adds a Friend to the Group permanently: the trigger in"
note "01-friend.sql makes their row, and there is no screen anywhere that"
note "removes one. Undoing it means deleting the auth user in the dashboard."
printf '\n'
say "So use a real Friend's real address — someone you were going to add"
say "anyway. This run IS their onboarding, and they choose the password."
printf '\n'
say "The signup screen is at  /sign-up  and nothing links to it, by design."
say "Locally that is  http://localhost:5173/sign-up  with \`yarn dev\` running."
printf '\n'
if confirm "Ready to walk a real Friend through it?"; then
  printf '\n'
  step "They open /sign-up and enter their address and a password."
  step "They should land straight on /setup — no confirmation screen, no email."
  step "They pick a name and a blob, and finish. The calendar opens."
  step "Their blob appears in everyone else's sidebar."
  printf '\n'
  note "While you are there, the other half of the criterion is free to check"
  note "and creates nothing: type any address that is NOT on the list and you"
  note "should get 'We could not create an account with those details.' plus"
  note "'Everyone here was added by hand...'. Their own address, already used,"
  note "gives exactly the same two sentences. That sameness is the feature."
  printf '\n'
  pause "Press Enter when they are through."
else
  SKIPPED+=("the acceptance signup (issue 14: 'an address on the list can sign up and lands in the setup flow')")
fi

finish
note "The allowlist is now the only door into this project."
note "Adding someone later: supabase/07-allowlist.sql §2 has the statement."
printf '\n'
